### ISSUE TITLE
Not all ID found in meta data of this GatingSet

### ISSUE THREAD

**Issue by JauntyJJS** [RGLab/QUALIFIER#48]
Hi,

I have this error after I managed to create the flowjo workspace and want to do some QA on the gated results

G is a Gating Set

> getQAStats(G)
> [1] "extracting stats..."
> Error in getQAStats(G) : 
>   Not all IDs for the current sample set are found in meta data of this GatingSet!

But I am pretty sure that this is all the fcs files for this workspace.
Is it possible to tell which ID is missing ?

Attached is the workspace file
and some fcs file. I will submit the rest later. 
[ws.zip](https://github.com/RGLab/QUALIFIER/files/89927/ws.zip)

[G DMSO.zip](https://github.com/RGLab/QUALIFIER/files/89930/G.DMSO.zip)

**Comment by JauntyJJS** [comment]
[F07-F10.zip](https://github.com/RGLab/QUALIFIER/files/90002/F07-F10.zip)

[F03-F06.zip](https://github.com/RGLab/QUALIFIER/files/90023/F03-F06.zip)

**Comment by JauntyJJS** [comment]
[E08-E10,F02.zip](https://github.com/RGLab/QUALIFIER/files/90048/E08-E10.F02.zip)

**Comment by JauntyJJS** [comment]
[E05-E07.zip](https://github.com/RGLab/QUALIFIER/files/90104/E05-E07.zip)

[E02-E04.zip](https://github.com/RGLab/QUALIFIER/files/91219/E02-E04.zip)

That is all the FCS data required.

**Comment by JauntyJJS** [comment]
After reading the manual, it seems that the metadata is a csv file that contains the name of the FCS file for each row. 
My question for the name of the FCS file, must it be a file path as well ?

Regards,
Jeremy

**Comment by SamGG** [comment]
Hi,
A simple suggestions. Did you try to put FCS and workspace in the same directory and use it as your current working directory?
Best.

**Comment by mikejiang** [comment]
It is looking for the sample identifier column from your `pData(gs)`, which is defined by `QUALIFIER:::qa.par.get("idCol")`. You can change this to whatever column that can uniquely identify each FCS/sample, e.g. 

``` r
QUALIFIER:::qa.par.set("idCol", "name")
```

Then, you should have no problem to run `getQAStats`.

**Comment by JauntyJJS** [comment]
Sorry for the late reply.

I have taken a look at what pData does and this is what I have.

> pData(GT)
>                                                      name
> E02 LSW124-10uM.fcs_71132             E02 LSW124-10uM.fcs
> E03 LSW124-2uM.fcs_73532               E03 LSW124-2uM.fcs
> E04 LSW124-0.4uM.fcs_95811           E04 LSW124-0.4uM.fcs
> E05 LSW124-0.08uM.fcs_98262         E05 LSW124-0.08uM.fcs
> E06 LSW124-0.016uM.fcs_92674       E06 LSW124-0.016uM.fcs
> E07 LSW124-0.0032uM.fcs_96766     E07 LSW124-0.0032uM.fcs
> E08 LSW124-0.00064uM.fcs_100000  E08 LSW124-0.00064uM.fcs
> E09 LSW124-0.000128uM.fcs_95867 E09 LSW124-0.000128uM.fcs
> E10 LSW124-0.000026uM.fcs_88968 E10 LSW124-0.000026uM.fcs
> F02 LSW124-10uM.fcs_34926             F02 LSW124-10uM.fcs
> F03 LSW124-2uM.fcs_51296               F03 LSW124-2uM.fcs
> F04 LSW124-0.4uM.fcs_67395           F04 LSW124-0.4uM.fcs
> F05 LSW124-0.08uM.fcs_69206         F05 LSW124-0.08uM.fcs
> F06 LSW124-0.016uM.fcs_70183       F06 LSW124-0.016uM.fcs
> F07 LSW124-0.0032uM.fcs_65632     F07 LSW124-0.0032uM.fcs
> F08 LSW124-0.00064uM.fcs_61350   F08 LSW124-0.00064uM.fcs
> F09 LSW124-0.000128uM.fcs_70075 F09 LSW124-0.000128uM.fcs
> F10 LSW124-0.000026uM.fcs_62865 F10 LSW124-0.000026uM.fcs
> G02 DMSO.fcs_28079                           G02 DMSO.fcs
> G03 DMSO.fcs_42582                           G03 DMSO.fcs
> G04 DMSO.fcs_38573                           G04 DMSO.fcs
> G05 DMSO.fcs_51200                           G05 DMSO.fcs
> G06 DMSO.fcs_45104                           G06 DMSO.fcs

and then have an idea why QUALIFIER:::qa.par.set("idCol", "name") works.

Looking at QUALIFIER:::qa.par.get("idCol") initially, it says "fileid" instead of "name" . Is this something that QUALIFIER assign by default or is it because of the nature of the FCS file ?

**Comment by JauntyJJS** [comment]
I also have another question.

I realised that when I did a getQAStats(G[[1]]) on a particular Gating hierarchy directly after loading the workspace into R, I got channel and stain columns as NA.

However, for the example dataset ITNQASTUDY, this is not the case. 

May I ask if this two columns is meant to be input manually or can be obtained from the flowjo workspace which is later passed into R ?

**Comment by mikejiang** [comment]
There are two types of `stats`:
- channel-specific: like `MFI`
- non channel-specific: like `counts` or `proportion`, which is why you see `NA` 

`MFI` is not calculated by default for the sake of computing time. You can enable it by

``` r
getQAStats(G[[1]], isMFI = T)
```

**Comment by JauntyJJS** [comment]
I have tried getQAStats(G[[1]], isMFI = T) and it works
.
channel stain      stats        value                                       node
FL1-A FL1-A proportion 9.936236e-01         /Lymphocytes/SingleCells/B220+/p8+
FL1-A FL1-A      count  2.711400e+04         /Lymphocytes/SingleCells/B220+/p8+
FL1-A FL1-A        MFI  9.997232e+01         /Lymphocytes/SingleCells/B220+/p8+

However, I am actually more interested in obtaining the raw values  of the MFI instead of the transformed values (172888.61 instead of 99.97232)

What I did  was to use the inverse transformation in flowWorkspace to get those values

FlowData=list()
for (things in c(1:length(G))) {
  GatingHierarchy = G[[things]]

  p8_flowframe_data = getData(G[[things]],"p8+")
  p8_data = as.data.table(p8_flowframe_data@exprs)
  inverse_transform_list = getTransformations(G[[things]], inverse = TRUE)
  p8_data_FLA = p8_data$`FL1-A`
  P8Median_Signal = median(sapply(p8_data_FLA,inverse_transform_list$`FL1-A`))
  print(P8Median_Signal)
 }

I was wondering if getQAStats has a similar function to the above and can output the raw values of the MFI of a given channel for a given population.

Also, can I clarify that if the count and population values given in getQAStats is directly extracted from getPopStats() from flowWorksapce right ?

**Comment by mikejiang** [comment]
Yes, both `getQAStats` and `getPopStats` get `count` and `proportions` from the same source.

I added the option to extract the `MFI` in raw scale in `version 1.15.2`. e.g.

``` r
getQAStats(gs[[1]], isRaw = T, isMFI = T)
```
